cluster_name: kbj-rancher
kubernetes_version: "v1.20.15-rancher1-2"
enable_cri_dockerd: true

nodes:
    - address: prod-k8s-rancher-01 #The public DNS or IP address
      user: rkeuser #A user that can run docker commands
      internal_address: 10.250.250.177 #The private DNS or IP address for internal cluster traffic
      role: [controlplane, etcd, worker]
    - address: prod-k8s-rancher-02 #The public DNS or IP address
      user: rkeuser #A user that can run docker commands
      internal_address: 10.250.250.178 #The private DNS or IP address for internal cluster traffic
      role: [controlplane, etcd, worker]
    - address: prod-k8s-rancher-03 #The public DNS or IP address
      user: rkeuser #A user that can run docker commands
      internal_address: 10.250.250.179 #The private DNS or IP address for internal cluster traffic
      role: [controlplane, etcd, worker]

network:
  plugin: calico

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

# Disable ingress
ingress:
    provider: none