apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-ing
  namespace: cattle-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: rancher.kbjcapital.co.th
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: rancher
            port:
              number: 80